# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Oxigen Salud
org_slug: oxigensalud
rebel_module_groups: []
repo_description: Customization addons for Oxigen Salud.
repo_name: Oxigensalud Odoo Addons
repo_slug: odoo-addons
repo_website: https://github.com/oxigensalud/odoo-addons
travis_apt_packages: []
travis_apt_sources: []
